### ISSUE TITLE
Mirai Dialogue - đã note QC (chờ sửa)

### ISSUE THREAD

**Issue by moch1oka** [realKiOZ/anime-subs#4]
Cái này e lỡ commit thẳng lên main từ mấy hôm trước rùi á :D
https://github.com/Good-Subs-Good-Anime-Vietsub/anime-subs/commit/1450078b18422d0a5162e4d9e50365bfcf9436ff

**Comment by realKiOZ** [comment]
Ok, a nhớ mà, nhưng mấy nay nhà có việc, rượu các thứ ko làm đc
