### ISSUE TITLE
Bổ sung chút cho cái readme

### ISSUE THREAD

**Issue by NeverSm1le** [realKiOZ/anime-subs#5]
Có 1 tool cực tốt mình hay dùng mux nhiều file thay cho mkvtoolnix là MKV Muxing Batch GUI, và mxplayer xem tốt hơn mpv trên android khá nhiều (mỗi tội qc hơi nhiều)

Thế thôi, cám ơn nhóm nhé, bộ sub quá tuyệt.

**Comment by realKiOZ** [comment]
OK nha KhôngBaoGiờCườ1, để mình bổ sung MKV Muxing Batch GUI.

Nhưng còn MXplayer thì thực sự load font và sub thua mpv-android khá nhiều, sub nhẹ ít font thì không sao, nhưng nếu nặng một chút là dễ lag lắm.

**Comment by tuilakhanh** [comment]
> mxplayer xem tốt hơn mpv trên android khá nhiều

Theo mình thấy thì MXPlayer có UI và nhiều tính năng hơn mpv-android thôi.

MXPlayer sẽ phải tốn một khoản thời gian khá lâu để load font lẫn sub ass so với mpv-android mở lền là chạy không cần load gì hết cả chưa kể phần font vs sub ass của tụi mình làm khá nặng nên sử dụng MXPlayer sẽ tốn khá nhiều thời gian để đọc.

Tụi mình sử dụng libass để làm sub mà hiện tại mpv là player có tính tương thích và tốc độ sử lý nhanh nhất trong đám player hiện nay. Ngoài ra sử dụng chung 1 player cho đa nền tảng giúp cho tụi mình có thể đảm bảo rằng sub có thể render đồng nhất giữa toàn bộ nền tảng. MXPlayer đồng ý là có sử dụng libass tuy nhiên theo mình thấy MXPlayer implement libass thực sự không tốt bằng mpv.

MXPlayer có rất nhiều quảng cáo và không phải ai cũng có thể mua bản trả phí (trừ trường hợp crack). mpv-android thì không có quảng cáo và được open-source.

![Screenshot_20230420-182219_MX Player](https://user-images.githubusercontent.com/17153084/233352028-4721e8b3-6e60-4712-a399-fc72c31f9a5f.png)
